{{- if .Values.middleware.postgres.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: {{ include "tcm.namespace" . }}
  labels:
    {{- include "tcm.serviceLabels" (list . "postgres" "database") | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - name: tcp-pg
      port: {{ .Values.middleware.postgres.port }}
      targetPort: tcp-pg
      protocol: TCP
  selector:
    {{- include "tcm.selectorLabels" (list . "postgres") | nindent 4 }}
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres
  namespace: {{ include "tcm.namespace" . }}
  labels:
    {{- include "tcm.serviceLabels" (list . "postgres" "database") | nindent 4 }}
spec:
  serviceName: postgres
  replicas: {{ .Values.middleware.postgres.replicas }}
  podManagementPolicy: OrderedReady
  selector:
    matchLabels:
      {{- include "tcm.selectorLabels" (list . "postgres") | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "tcm.serviceLabels" (list . "postgres" "database") | nindent 8 }}
    spec:
      securityContext:
        fsGroup: 999
      containers:
        - name: postgres
          image: {{ .Values.middleware.postgres.image }}
          imagePullPolicy: {{ .Values.global.imagePullPolicy }}
          ports:
            - name: tcp-pg
              containerPort: 5432
              protocol: TCP
          env:
            - name: POSTGRES_USER
              valueFrom:
                configMapKeyRef:
                  name: {{ include "tcm.fullName" . }}-config
                  key: TCM_DB_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "tcm.fullName" . }}-secret
                  key: TCM_DB_PASSWORD
            - name: POSTGRES_DB
              valueFrom:
                configMapKeyRef:
                  name: {{ include "tcm.fullName" . }}-config
                  key: TCM_DB_DBNAME
            - name: TZ
              value: Asia/Shanghai
          resources:
            {{- toYaml .Values.middleware.postgres.resources | nindent 12 }}
          readinessProbe:
            exec:
              command: ["sh", "-c", "pg_isready -U $(POSTGRES_USER) -d $(POSTGRES_DB)"]
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 6
          livenessProbe:
            exec:
              command: ["sh", "-c", "pg_isready -U $(POSTGRES_USER) -d $(POSTGRES_DB)"]
            initialDelaySeconds: 30
            periodSeconds: 20
            timeoutSeconds: 5
            failureThreshold: 6
          volumeMounts:
            - name: data
              mountPath: /var/lib/postgresql/data
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        storageClassName: {{ .Values.global.storageClass }}
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: {{ .Values.middleware.postgres.storage }}
{{- end }}
