// Code generated by hand (acts as the wire_gen.go replacement). DO NOT EDIT.
//
// This file is the non-wireinject counterpart to wire.go. It assembles the
// dependency graph manually so the service can be built without running the
// google/wire code generator. The structure mirrors what wire would emit.

package main

import (
	"context"
	"fmt"
	"time"

	"gorm.io/driver/postgres"
	"gorm.io/gorm"
	gormlogger "gorm.io/gorm/logger"

	"tcm-history-ai/backend/graph-service/internal/application/usecase"
	"tcm-history-ai/backend/graph-service/internal/conf"
	"tcm-history-ai/backend/graph-service/internal/controller"
	"tcm-history-ai/backend/graph-service/internal/domain/event"
	"tcm-history-ai/backend/graph-service/internal/domain/repository"
	"tcm-history-ai/backend/graph-service/internal/domain/service"
	"tcm-history-ai/backend/graph-service/internal/infrastructure/eventbus"
	"tcm-history-ai/backend/graph-service/internal/infrastructure/neo4j"
	"tcm-history-ai/backend/graph-service/internal/infrastructure/persistence"
	"tcm-history-ai/backend/pkg/rabbitmq"
)

// App holds every wired dependency required to serve HTTP traffic.
type App struct {
	nodeRepo     repository.GraphNodeRepository
	edgeRepo     repository.GraphEdgeRepository
	syncLogRepo  repository.GraphSyncLogRepository
	graphStore   service.GraphStore
	publisher    event.EventPublisher

	nodeUC  *usecase.NodeUseCase
	edgeUC  *usecase.EdgeUseCase
	queryUC *usecase.QueryUseCase
	syncUC  *usecase.SyncUseCase

	db     *gorm.DB
	neo4j  *neo4j.Client
	pub    *eventbus.RabbitMQEventPublisher
	sub    *eventbus.RabbitMQEventSubscriber
}

// ControllerDeps returns the bundle of controllers required by the router.
func (a *App) ControllerDeps() *controller.Deps {
	return &controller.Deps{
		Node:  controller.NewNodeController(a.nodeUC),
		Edge:  controller.NewEdgeController(a.edgeUC),
		Query: controller.NewQueryController(a.queryUC),
		Sync:  controller.NewSyncController(a.syncUC),
	}
}

// StartSubscriber launches the RabbitMQ consumer. The handler dispatches each
// delivered event into SyncUseCase.Dispatch (doc/05 §5.6). The call blocks
// until ctx is cancelled; the stub implementation returns immediately so
// development can proceed without a live broker.
func (a *App) StartSubscriber(ctx context.Context) error {
	handler := func(c context.Context, routingKey string, body []byte) error {
		return a.syncUC.Dispatch(c, routingKey, body)
	}
	return a.sub.Subscribe(ctx, handler)
}

// InitializeApp builds the full dependency graph from configuration.
// The returned cleanup function releases all acquired resources.
func InitializeApp(cfg *conf.Config) (*App, func(), error) {
	app := &App{}
	cleanups := make([]func(), 0)
	cleanup := func() {
		for i := len(cleanups) - 1; i >= 0; i-- {
			cleanups[i]()
		}
	}

	db, err := newDB(cfg)
	if err != nil {
		cleanup()
		return nil, nil, fmt.Errorf("open db: %w", err)
	}
	app.db = db

	// Repositories (PostgreSQL-backed mirror tables).
	app.nodeRepo = persistence.NewGraphNodeRepo(db)
	app.edgeRepo = persistence.NewGraphEdgeRepo(db)
	app.syncLogRepo = persistence.NewGraphSyncLogRepo(db)

	// Neo4j client (GraphStore). 在 enabled=false 时为内存 stub（doc/05 §5.7）。
	neo4jClient := neo4j.New(neo4j.Config{
		Host:     cfg.Neo4j.Host,
		Port:     cfg.Neo4j.Port,
		User:     cfg.Neo4j.User,
		Password: cfg.Neo4j.Password,
		Enabled:  cfg.Neo4j.Enabled,
	})
	app.neo4j = neo4jClient
	app.graphStore = neo4jClient
	// Best-effort: 建立 8 类节点唯一约束与索引（doc/05 §5.8）。
	_ = neo4jClient.EnsureConstraints(context.Background())

	// Event publisher (RabbitMQ).
	rmqCfg := rabbitmq.Config{
		Host:     cfg.RabbitMQ.Host,
		Port:     cfg.RabbitMQ.Port,
		User:     cfg.RabbitMQ.User,
		Password: cfg.RabbitMQ.Password,
		VHost:    cfg.RabbitMQ.VHost,
	}
	pub := eventbus.NewRabbitMQEventPublisher(rmqCfg)
	app.pub = pub
	app.publisher = pub
	cleanups = append(cleanups, func() { _ = pub.Close() })

	// Event subscriber (RabbitMQ). Subscribe is invoked asynchronously from
	// main after the HTTP server starts; the handler dispatches into SyncUseCase.
	app.sub = eventbus.NewRabbitMQEventSubscriber(rmqCfg, "graph-service.sync")

	// Use cases.
	app.nodeUC = usecase.NewNodeUseCase(app.nodeRepo, app.graphStore, app.publisher)
	app.edgeUC = usecase.NewEdgeUseCase(app.edgeRepo, app.graphStore, app.publisher)
	app.queryUC = usecase.NewQueryUseCase(app.graphStore)
	app.syncUC = usecase.NewSyncUseCase(app.graphStore, app.syncLogRepo)

	cleanups = append(cleanups, func() {
		sqlDB, _ := db.DB()
		if sqlDB != nil {
			_ = sqlDB.Close()
		}
	})

	return app, cleanup, nil
}

// newDB opens a GORM *gorm.DB using the Postgres driver.
func newDB(cfg *conf.Config) (*gorm.DB, error) {
	level := gormlogger.Warn
	switch cfg.DB.LogLevel {
	case "silent":
		level = gormlogger.Silent
	case "error":
		level = gormlogger.Error
	case "warn":
		level = gormlogger.Warn
	case "info":
		level = gormlogger.Info
	}
	gormCfg := &gorm.Config{
		Logger: gormlogger.Default.LogMode(level),
	}
	db, err := gorm.Open(postgres.Open(cfg.DB.DSN()), gormCfg)
	if err != nil {
		return nil, err
	}
	sqlDB, err := db.DB()
	if err != nil {
		return nil, err
	}
	if cfg.DB.MaxOpenConns > 0 {
		sqlDB.SetMaxOpenConns(cfg.DB.MaxOpenConns)
	}
	if cfg.DB.MaxIdleConns > 0 {
		sqlDB.SetMaxIdleConns(cfg.DB.MaxIdleConns)
	}
	if cfg.DB.ConnMaxLifetime > 0 {
		sqlDB.SetConnMaxLifetime(time.Duration(cfg.DB.ConnMaxLifetime) * time.Second)
	}
	return db, nil
}
