// Code generated by hand (acts as the wire_gen.go replacement). DO NOT EDIT.
//
// This file is the non-wireinject counterpart to wire.go. It assembles the
// dependency graph manually so the service can be built without running the
// google/wire code generator. The structure mirrors what wire would emit.

package main

import (
	"context"
	"fmt"
	"time"

	"gorm.io/driver/postgres"
	"gorm.io/gorm"
	gormlogger "gorm.io/gorm/logger"

	"tcm-history-ai/backend/history-service/internal/application/usecase"
	"tcm-history-ai/backend/history-service/internal/conf"
	"tcm-history-ai/backend/history-service/internal/controller"
	"tcm-history-ai/backend/history-service/internal/domain/event"
	"tcm-history-ai/backend/history-service/internal/infrastructure/eventbus"
	"tcm-history-ai/backend/history-service/internal/infrastructure/persistence"
	"tcm-history-ai/backend/history-service/internal/infrastructure/search"
	"tcm-history-ai/backend/history-service/internal/infrastructure/storage"
	"tcm-history-ai/backend/pkg/rabbitmq"
)

// App holds every wired dependency required to serve HTTP traffic.
type App struct {
	dynastyRepo      *persistence.DynastyRepo
	personRepo       *persistence.PersonRepo
	schoolRepo       *persistence.SchoolRepo
	bookRepo         *persistence.BookRepo
	eventRepo        *persistence.EventRepo
	prescriptionRepo *persistence.PrescriptionRepo
	medicineRepo     *persistence.MedicineRepo
	diseaseRepo      *persistence.DiseaseRepo

	dynastyUC  *usecase.DynastyUseCase
	personUC   *usecase.PersonUseCase
	schoolUC   *usecase.SchoolUseCase
	bookUC     *usecase.BookUseCase
	eventUC    *usecase.EventUseCase
	prescUC    *usecase.PrescriptionUseCase
	medicineUC *usecase.MedicineUseCase
	diseaseUC  *usecase.DiseaseUseCase
	searchUC   *usecase.SearchUseCase
	uploadUC   *usecase.UploadUseCase

	db        *gorm.DB
	meili     *search.MeiliClient
	minio     *storage.MinIOClient
	publisher event.EventPublisher
}

// ControllerDeps returns the bundle of controllers required by the router.
func (a *App) ControllerDeps() *controller.Deps {
	return &controller.Deps{
		Dynasty:      controller.NewDynastyController(a.dynastyUC),
		Person:       controller.NewPersonController(a.personUC),
		School:       controller.NewSchoolController(a.schoolUC),
		Book:         controller.NewBookController(a.bookUC),
		Event:        controller.NewEventController(a.eventUC),
		Prescription: controller.NewPrescriptionController(a.prescUC),
		Medicine:     controller.NewMedicineController(a.medicineUC),
		Disease:      controller.NewDiseaseController(a.diseaseUC),
		Search:       controller.NewSearchController(a.searchUC),
		Upload:       controller.NewUploadController(a.uploadUC),
	}
}

// InitializeApp builds the full dependency graph from configuration.
// The returned cleanup function releases all acquired resources.
func InitializeApp(cfg *conf.Config) (*App, func(), error) {
	app := &App{}
	cleanups := make([]func(), 0)
	cleanup := func() {
		for i := len(cleanups) - 1; i >= 0; i-- {
			cleanups[i]()
		}
	}

	db, err := newDB(cfg)
	if err != nil {
		cleanup()
		return nil, nil, fmt.Errorf("open db: %w", err)
	}
	app.db = db

	// Repositories.
	app.dynastyRepo = persistence.NewDynastyRepo(db)
	app.personRepo = persistence.NewPersonRepo(db)
	app.schoolRepo = persistence.NewSchoolRepo(db)
	app.bookRepo = persistence.NewBookRepo(db)
	app.eventRepo = persistence.NewEventRepo(db)
	app.prescriptionRepo = persistence.NewPrescriptionRepo(db)
	app.medicineRepo = persistence.NewMedicineRepo(db)
	app.diseaseRepo = persistence.NewDiseaseRepo(db)

	// Cross-cutting infrastructure.
	app.meili = search.NewMeiliClient(cfg.Meili.Host, cfg.Meili.Port, cfg.Meili.APIKey, cfg.Meili.IndexPrefix)

	mc, err := storage.NewMinIOClient(cfg.MinIO.Endpoint, cfg.MinIO.AccessKey, cfg.MinIO.SecretKey, cfg.MinIO.BucketName, cfg.MinIO.UseSSL)
	if err != nil {
		cleanup()
		return nil, nil, fmt.Errorf("init minio: %w", err)
	}
	app.minio = mc
	// Best-effort bucket creation; a missing broker must not block startup.
	_ = mc.EnsureBucket(context.Background())

	rmqCfg := rabbitmq.Config{
		Host:     cfg.RabbitMQ.Host,
		Port:     cfg.RabbitMQ.Port,
		User:     cfg.RabbitMQ.User,
		Password: cfg.RabbitMQ.Password,
		VHost:    cfg.RabbitMQ.VHost,
	}
	app.publisher = eventbus.NewRabbitMQEventPublisher(rmqCfg)
	if pub, ok := app.publisher.(*eventbus.RabbitMQEventPublisher); ok {
		cleanups = append(cleanups, func() { _ = pub.Close() })
	}

	// Use cases.
	app.dynastyUC = usecase.NewDynastyUseCase(app.dynastyRepo, app.publisher)
	app.personUC = usecase.NewPersonUseCase(app.personRepo, app.publisher)
	app.schoolUC = usecase.NewSchoolUseCase(app.schoolRepo)
	app.bookUC = usecase.NewBookUseCase(app.bookRepo, app.publisher)
	app.eventUC = usecase.NewEventUseCase(app.eventRepo)
	app.prescUC = usecase.NewPrescriptionUseCase(app.prescriptionRepo)
	app.medicineUC = usecase.NewMedicineUseCase(app.medicineRepo)
	app.diseaseUC = usecase.NewDiseaseUseCase(app.diseaseRepo)
	app.searchUC = usecase.NewSearchUseCase(app.meili)
	app.uploadUC = usecase.NewUploadUseCase(app.minio)

	cleanups = append(cleanups, func() {
		sqlDB, _ := db.DB()
		if sqlDB != nil {
			_ = sqlDB.Close()
		}
	})

	return app, cleanup, nil
}

// newDB opens a GORM *gorm.DB using the Postgres driver.
func newDB(cfg *conf.Config) (*gorm.DB, error) {
	level := gormlogger.Warn
	switch cfg.DB.LogLevel {
	case "silent":
		level = gormlogger.Silent
	case "error":
		level = gormlogger.Error
	case "warn":
		level = gormlogger.Warn
	case "info":
		level = gormlogger.Info
	}
	gormCfg := &gorm.Config{
		Logger: gormlogger.Default.LogMode(level),
	}
	db, err := gorm.Open(postgres.Open(cfg.DB.DSN()), gormCfg)
	if err != nil {
		return nil, err
	}
	sqlDB, err := db.DB()
	if err != nil {
		return nil, err
	}
	if cfg.DB.MaxOpenConns > 0 {
		sqlDB.SetMaxOpenConns(cfg.DB.MaxOpenConns)
	}
	if cfg.DB.MaxIdleConns > 0 {
		sqlDB.SetMaxIdleConns(cfg.DB.MaxIdleConns)
	}
	if cfg.DB.ConnMaxLifetime > 0 {
		sqlDB.SetConnMaxLifetime(time.Duration(cfg.DB.ConnMaxLifetime) * time.Second)
	}
	return db, nil
}
