// Code generated by hand (acts as the wire_gen.go replacement). DO NOT EDIT.
//
// This file is the non-wireinject counterpart to wire.go. It assembles the
// dependency graph manually so the service can be built without running the
// google/wire code generator. The structure mirrors what wire would emit.

package main

import (
	"context"
	"fmt"
	"time"

	"gorm.io/driver/postgres"
	"gorm.io/gorm"
	gormlogger "gorm.io/gorm/logger"

	"tcm-history-ai/backend/ai-service/internal/application/usecase"
	"tcm-history-ai/backend/ai-service/internal/conf"
	"tcm-history-ai/backend/ai-service/internal/controller"
	"tcm-history-ai/backend/ai-service/internal/domain/event"
	"tcm-history-ai/backend/ai-service/internal/domain/service"
	"tcm-history-ai/backend/ai-service/internal/infrastructure/eventbus"
	"tcm-history-ai/backend/ai-service/internal/infrastructure/llm"
	"tcm-history-ai/backend/ai-service/internal/infrastructure/mcp"
	"tcm-history-ai/backend/ai-service/internal/infrastructure/persistence"
	"tcm-history-ai/backend/ai-service/internal/infrastructure/prompt"
	"tcm-history-ai/backend/ai-service/internal/infrastructure/retrieval"
	"tcm-history-ai/backend/ai-service/internal/infrastructure/tool"
	"tcm-history-ai/backend/pkg/logger"
	"tcm-history-ai/backend/pkg/outbox"
	"tcm-history-ai/backend/pkg/rabbitmq"
)

// App holds every wired dependency required to serve HTTP traffic.
type App struct {
	convRepo    *persistence.ConversationRepo
	msgRepo     *persistence.MessageRepo
	promptRepo  *persistence.PromptTemplateRepo
	toolRepo    *persistence.ToolRepo
	agentRepo   *persistence.AgentRunRepo
	tokenUsageRepo *persistence.TokenUsageRepo
	tokenQuotaRepo *persistence.TokenQuotaRepo

	chatUC   *usecase.ChatUseCase
	agentUC  *usecase.AgentUseCase
	promptUC *usecase.PromptUseCase
	toolUC   *usecase.ToolUseCase
	tokenUC  *usecase.TokenUseCase

	db         *gorm.DB
	llm        service.LLMProvider
	renderer   service.PromptRenderer
	toolExec   service.ToolExecutor
	retriever  service.RetrievalClient
	publisher  event.EventPublisher
	outboxRepo *outbox.Repository
	Relay      *outbox.Relay

	mcpRegistry *mcp.Registry
	mcpServer   *mcp.Server
}

// ControllerDeps returns the bundle of controllers required by the router.
func (a *App) ControllerDeps() *controller.Deps {
	return &controller.Deps{
		Chat:   controller.NewChatController(a.chatUC),
		Agent:  controller.NewAgentController(a.agentUC),
		Prompt: controller.NewPromptController(a.promptUC),
		Tool:   controller.NewToolController(a.toolUC),
		Token:  controller.NewTokenController(a.tokenUC),
		MCP:    controller.NewMCPController(a.mcpServer),
	}
}

// InitializeApp builds the full dependency graph from configuration.
// The returned cleanup function releases all acquired resources.
func InitializeApp(cfg *conf.Config) (*App, func(), error) {
	app := &App{}
	cleanups := make([]func(), 0)
	cleanup := func() {
		for i := len(cleanups) - 1; i >= 0; i-- {
			cleanups[i]()
		}
	}

	db, err := newDB(cfg)
	if err != nil {
		cleanup()
		return nil, nil, fmt.Errorf("open db: %w", err)
	}
	app.db = db

	// Repositories.
	app.convRepo = persistence.NewConversationRepo(db)
	app.msgRepo = persistence.NewMessageRepo(db)
	app.promptRepo = persistence.NewPromptTemplateRepo(db)
	app.toolRepo = persistence.NewToolRepo(db)
	app.agentRepo = persistence.NewAgentRunRepo(db)
	app.tokenUsageRepo = persistence.NewTokenUsageRepo(db)
	app.tokenQuotaRepo = persistence.NewTokenQuotaRepo(db)

	// LLM provider (stub when enabled=false).
	provider, err := llm.New(llm.Config{
		Provider: cfg.LLM.Provider,
		Endpoint: cfg.LLM.Endpoint,
		APIKey:   cfg.LLM.APIKey,
		Model:    cfg.LLM.Model,
		Dim:      cfg.LLM.Dim,
		Timeout:  cfg.LLM.Timeout,
		Enabled:  cfg.LLM.Enabled,
	})
	if err != nil {
		cleanup()
		return nil, nil, fmt.Errorf("init llm provider: %w", err)
	}
	app.llm = provider

	// Prompt renderer.
	app.renderer = prompt.New()

	// Tool executor (HTTP-based stub when enabled=false).
	app.toolExec = tool.New(app.toolRepo, tool.Config{
		HTTPTimeout: cfg.LLM.Timeout,
		Enabled:     cfg.LLM.Enabled,
	})

	// Retrieval client (HTTP-based; empty URLs degrade to no-op).
	app.retriever = retrieval.New(retrieval.Config{
		KnowledgeURL: cfg.Services.KnowledgeURL,
		GraphURL:     cfg.Services.GraphURL,
		Timeout:      cfg.Services.Timeout,
	})

	// Event publisher (RabbitMQ).
	rmqCfg := rabbitmq.Config{
		Host:     cfg.RabbitMQ.Host,
		Port:     cfg.RabbitMQ.Port,
		User:     cfg.RabbitMQ.User,
		Password: cfg.RabbitMQ.Password,
		VHost:    cfg.RabbitMQ.VHost,
	}
	pub := eventbus.NewRabbitMQEventPublisher(rmqCfg)
	app.publisher = pub
	cleanups = append(cleanups, func() { _ = pub.Close() })

	// Transactional outbox (doc/02 §6.2): business write + event enqueue
	// share one DB tx; a background Relay polls and delivers to RabbitMQ.
	app.outboxRepo = outbox.NewRepository(db)
	rawPub := eventbus.NewRawPublisher(pub.Inner())
	app.Relay = outbox.NewRelay(
		app.outboxRepo, rawPub,
		outbox.WithLogger(logger.Default()),
	)

	// Use cases.
	app.chatUC = usecase.NewChatUseCase(
		app.convRepo, app.msgRepo, app.promptRepo,
		app.llm, app.renderer, app.publisher,
	)
	app.agentUC = usecase.NewAgentUseCase(
		app.convRepo, app.msgRepo, app.agentRepo, app.promptRepo, app.toolRepo,
		app.llm, app.toolExec, app.retriever, app.renderer, app.publisher,
		db, app.outboxRepo,
	)
	app.promptUC = usecase.NewPromptUseCase(app.promptRepo, app.renderer)
	app.toolUC = usecase.NewToolUseCase(app.toolRepo, app.toolExec)
	app.tokenUC = usecase.NewTokenUseCase(app.tokenUsageRepo, app.tokenQuotaRepo)

	// MCP Server.
	app.mcpRegistry = mcp.NewRegistry(app.toolRepo)
	// Load custom tools from DB; built-ins are registered next.
	_ = app.mcpRegistry.Load(context.Background())
	mcpExec := mcp.NewExecutorAdapter(app.toolExec)
	app.mcpServer = mcp.NewServer(app.mcpRegistry, mcpExec)
	app.mcpServer.RegisterBuiltinTools()

	cleanups = append(cleanups, func() {
		sqlDB, _ := db.DB()
		if sqlDB != nil {
			_ = sqlDB.Close()
		}
	})

	return app, cleanup, nil
}

// newDB opens a GORM *gorm.DB using the Postgres driver.
func newDB(cfg *conf.Config) (*gorm.DB, error) {
	level := gormlogger.Warn
	switch cfg.DB.LogLevel {
	case "silent":
		level = gormlogger.Silent
	case "error":
		level = gormlogger.Error
	case "warn":
		level = gormlogger.Warn
	case "info":
		level = gormlogger.Info
	}
	gormCfg := &gorm.Config{
		Logger: gormlogger.Default.LogMode(level),
	}
	db, err := gorm.Open(postgres.Open(cfg.DB.DSN()), gormCfg)
	if err != nil {
		return nil, err
	}
	sqlDB, err := db.DB()
	if err != nil {
		return nil, err
	}
	if cfg.DB.MaxOpenConns > 0 {
		sqlDB.SetMaxOpenConns(cfg.DB.MaxOpenConns)
	}
	if cfg.DB.MaxIdleConns > 0 {
		sqlDB.SetMaxIdleConns(cfg.DB.MaxIdleConns)
	}
	if cfg.DB.ConnMaxLifetime > 0 {
		sqlDB.SetConnMaxLifetime(time.Duration(cfg.DB.ConnMaxLifetime) * time.Second)
	}
	return db, nil
}