// Code generated by hand (acts as the wire_gen.go replacement). DO NOT EDIT.
//
// This file is the non-wireinject counterpart to wire.go. It assembles the
// dependency graph manually so the service can be built without running the
// google/wire code generator. The structure mirrors what wire would emit.

package main

import (
	"context"
	"encoding/json"
	"fmt"
	"time"

	"gorm.io/driver/postgres"
	"gorm.io/gorm"
	gormlogger "gorm.io/gorm/logger"
	"go.uber.org/zap"

	"tcm-history-ai/backend/learning-service/internal/application/usecase"
	"tcm-history-ai/backend/learning-service/internal/conf"
	"tcm-history-ai/backend/learning-service/internal/controller"
	"tcm-history-ai/backend/learning-service/internal/domain/event"
	"tcm-history-ai/backend/learning-service/internal/infrastructure/aiclient"
	"tcm-history-ai/backend/learning-service/internal/infrastructure/cache"
	"tcm-history-ai/backend/learning-service/internal/infrastructure/eventbus"
	"tcm-history-ai/backend/learning-service/internal/infrastructure/persistence"
	"tcm-history-ai/backend/pkg/logger"
	"tcm-history-ai/backend/pkg/rabbitmq"
)

// App holds every wired dependency required to serve HTTP traffic.
type App struct {
	courseRepo     *persistence.CourseRepo
	lessonRepo     *persistence.LessonRepo
	enrollmentRepo *persistence.EnrollmentRepo
	recordRepo     *persistence.LearningRecordRepo
	examRepo       *persistence.ExamRepo
	questionRepo   *persistence.QuestionRepo
	attemptRepo    *persistence.ExamAttemptRepo
	wrongQRepo     *persistence.WrongQuestionRepo
	planRepo       *persistence.StudyPlanRepo

	courseUC   *usecase.CourseUseCase
	enrollUC   *usecase.EnrollmentUseCase
	recordUC   *usecase.LearningRecordUseCase
	examUC     *usecase.ExamUseCase
	attemptUC  *usecase.ExamAttemptUseCase
	wrongQUC   *usecase.WrongQuestionUseCase
	planUC     *usecase.StudyPlanUseCase
	dashboardUC *usecase.DashboardUseCase

	db        *gorm.DB
	redis     *cache.RedisClient
	aiClient  *aiclient.Client
	publisher event.EventPublisher
}

// ControllerDeps returns the bundle of controllers required by the router.
func (a *App) ControllerDeps() *controller.Deps {
	return &controller.Deps{
		Course:        controller.NewCourseController(a.courseUC),
		Enrollment:    controller.NewEnrollmentController(a.enrollUC),
		Record:        controller.NewLearningRecordController(a.recordUC),
		Exam:          controller.NewExamController(a.examUC),
		Attempt:       controller.NewExamAttemptController(a.attemptUC),
		WrongQuestion: controller.NewWrongQuestionController(a.wrongQUC),
		StudyPlan:     controller.NewStudyPlanController(a.planUC),
		Dashboard:     controller.NewDashboardController(a.dashboardUC),
	}
}

// InitializeApp builds the full dependency graph from configuration.
// The returned cleanup function releases all acquired resources.
func InitializeApp(cfg *conf.Config) (*App, func(), error) {
	app := &App{}
	cleanups := make([]func(), 0)
	cleanup := func() {
		for i := len(cleanups) - 1; i >= 0; i-- {
			cleanups[i]()
		}
	}

	db, err := newDB(cfg)
	if err != nil {
		cleanup()
		return nil, nil, fmt.Errorf("open db: %w", err)
	}
	app.db = db

	// Repositories.
	app.courseRepo = persistence.NewCourseRepo(db)
	app.lessonRepo = persistence.NewLessonRepo(db)
	app.enrollmentRepo = persistence.NewEnrollmentRepo(db)
	app.recordRepo = persistence.NewLearningRecordRepo(db)
	app.examRepo = persistence.NewExamRepo(db)
	app.questionRepo = persistence.NewQuestionRepo(db)
	app.attemptRepo = persistence.NewExamAttemptRepo(db)
	app.wrongQRepo = persistence.NewWrongQuestionRepo(db)
	app.planRepo = persistence.NewStudyPlanRepo(db)

	// Redis cache for learning progress and recent wrong questions.
	// Connection is lazy; a missing broker surfaces as a logged warning on
	// the first command, not as a startup failure.
	app.redis = cache.New(cfg.Redis)
	cleanups = append(cleanups, func() { _ = app.redis.Close() })

	// AI service client. Base URL empty -> offline/fallback mode.
	app.aiClient = aiclient.New(cfg.AIService)

	// RabbitMQ publisher. The underlying AMQP connection is opened lazily so
	// a missing broker does not break service startup.
	rmqCfg := rabbitmq.Config{
		Host:     cfg.RabbitMQ.Host,
		Port:     cfg.RabbitMQ.Port,
		User:     cfg.RabbitMQ.User,
		Password: cfg.RabbitMQ.Password,
		VHost:    cfg.RabbitMQ.VHost,
	}
	app.publisher = eventbus.NewRabbitMQEventPublisher(rmqCfg)
	if pub, ok := app.publisher.(*eventbus.RabbitMQEventPublisher); ok {
		cleanups = append(cleanups, func() { _ = pub.Close() })
	}

	// Best-effort event subscriber. Logs and exits if the broker is down;
	// never blocks startup.
	startEventSubscribers(context.Background(), rmqCfg, app)

	// Use cases.
	app.courseUC = usecase.NewCourseUseCase(app.courseRepo, app.lessonRepo, app.publisher)
	app.enrollUC = usecase.NewEnrollmentUseCase(app.enrollmentRepo, app.courseRepo, app.publisher)
	app.recordUC = usecase.NewLearningRecordUseCase(app.recordRepo, app.redis)
	app.examUC = usecase.NewExamUseCase(app.examRepo, app.questionRepo)
	app.attemptUC = usecase.NewExamAttemptUseCase(
		app.attemptRepo, app.examRepo, app.questionRepo, app.wrongQRepo, app.publisher, app.redis,
	)
	app.wrongQUC = usecase.NewWrongQuestionUseCase(app.wrongQRepo, app.redis)
	app.planUC = usecase.NewStudyPlanUseCase(app.planRepo, app.enrollmentRepo, app.aiClient)
	app.dashboardUC = usecase.NewDashboardUseCase(
		app.enrollmentRepo, app.recordRepo, app.attemptRepo, app.planRepo, app.wrongQRepo,
	)

	// Compile-time interface check: ensure the publisher satisfies the port.
	var _ event.EventPublisher = app.publisher

	cleanups = append(cleanups, func() {
		sqlDB, _ := db.DB()
		if sqlDB != nil {
			_ = sqlDB.Close()
		}
	})

	return app, cleanup, nil
}

// startEventSubscribers launches the background consumers for the three
// routing keys Learning Service listens to. Failures are logged and ignored.
func startEventSubscribers(ctx context.Context, cfg rabbitmq.Config, app *App) {
	// UserRegistered -> initialise learning profile (no-op in this version;
	// the handler is a placeholder for future extension).
	userSub := eventbus.NewSubscriber(cfg, "learning.user.registered",
		[]string{"user.registered"},
		func(_ context.Context, _ []byte) error {
			// In a future iteration this would seed default study plans /
			// enrollments. For now it is a logged no-op.
			logger.Default().Debug("learning subscriber: user.registered received")
			return nil
		})
	userSub.Start(ctx)

	// CourseCompleted -> refresh progress on study plans containing this course.
	courseSub := eventbus.NewSubscriber(cfg, "learning.course.completed",
		[]string{"learning.course.completed"},
		func(ctx context.Context, body []byte) error {
			var evt struct {
				UserID   int64 `json:"user_id"`
				CourseID int64 `json:"course_id"`
			}
			if err := json.Unmarshal(body, &evt); err != nil {
				logger.Default().Warn("learning subscriber: invalid course.completed payload",
					zap.Error(err))
				return nil
			}
			if evt.UserID > 0 && evt.CourseID > 0 {
				_ = app.planUC.RefreshForCourse(ctx, evt.UserID, evt.CourseID)
			}
			return nil
		})
	courseSub.Start(ctx)

	// ExamSubmitted -> wrong questions are persisted by the ExamAttempt use
	// case synchronously; the subscriber is a no-op placeholder.
	examSub := eventbus.NewSubscriber(cfg, "learning.exam.submitted",
		[]string{"learning.exam.submitted"},
		func(_ context.Context, _ []byte) error {
			logger.Default().Debug("learning subscriber: learning.exam.submitted received",
				zap.String("note", "wrong questions persisted by ExamAttempt use case"))
			return nil
		})
	examSub.Start(ctx)
}

// newDB opens a GORM *gorm.DB using the Postgres driver.
func newDB(cfg *conf.Config) (*gorm.DB, error) {
	level := gormlogger.Warn
	switch cfg.DB.LogLevel {
	case "silent":
		level = gormlogger.Silent
	case "error":
		level = gormlogger.Error
	case "warn":
		level = gormlogger.Warn
	case "info":
		level = gormlogger.Info
	}
	gormCfg := &gorm.Config{
		Logger: gormlogger.Default.LogMode(level),
	}
	db, err := gorm.Open(postgres.Open(cfg.DB.DSN()), gormCfg)
	if err != nil {
		return nil, err
	}
	sqlDB, err := db.DB()
	if err != nil {
		return nil, err
	}
	if cfg.DB.MaxOpenConns > 0 {
		sqlDB.SetMaxOpenConns(cfg.DB.MaxOpenConns)
	}
	if cfg.DB.MaxIdleConns > 0 {
		sqlDB.SetMaxIdleConns(cfg.DB.MaxIdleConns)
	}
	if cfg.DB.ConnMaxLifetime > 0 {
		sqlDB.SetConnMaxLifetime(time.Duration(cfg.DB.ConnMaxLifetime) * time.Second)
	}
	return db, nil
}
