//go:build wireinject
// +build wireinject

package main

import (
	"github.com/google/wire"

	"tcm-history-ai/backend/gateway/internal/conf"
)

// App bundles the wired dependencies required to serve HTTP traffic.
// In the wireinject build we let google/wire build it; in the regular build
// the hand-written wire_gen.go provides InitializeApp directly.

// InitializeApp wires every dependency needed to run the gateway.
// The implementation is generated by google/wire into wire_gen.go.
func InitializeApp(cfg *conf.Config) (*App, func(), error) {
	wire.Build(ProvidersSet)
	return nil, nil, nil
}

// ProvidersSet aggregates every provider used by the wire-driven graph. It
// is intentionally empty in this stub because the wire_gen.go replacement
// constructs the graph manually; the symbol exists so the wireinject build
// remains compilable for tooling.
var ProvidersSet = wire.NewSet()
