// Code generated by hand (acts as the wire_gen.go replacement). DO NOT EDIT.
//
// This file is the non-wireinject counterpart to wire.go. It assembles the
// dependency graph manually so the service can be built without running the
// google/wire code generator. The structure mirrors what wire would emit.

package main

import (
	"fmt"

	"tcm-history-ai/backend/gateway/internal/conf"
	"tcm-history-ai/backend/gateway/internal/controller"
	"tcm-history-ai/backend/gateway/internal/infrastructure/middleware"
)

// App holds every wired dependency required to serve HTTP traffic.
type App struct {
	cfg      *conf.Config
	chain    *middleware.Chain
	health   *controller.HealthController
	proxy    *controller.ProxyController
	resolver *controller.PathResolver
}

// ControllerDeps returns the bundle of controllers required by the router.
func (a *App) ControllerDeps() *controller.Deps {
	return &controller.Deps{
		Health: a.health,
		Proxy:  a.proxy,
	}
}

// MiddlewareChain returns the cross-cutting middleware chain.
func (a *App) MiddlewareChain() *middleware.Chain { return a.chain }

// InitializeApp builds the full dependency graph from configuration.
// The returned cleanup function releases all acquired resources.
func InitializeApp(cfg *conf.Config) (*App, func(), error) {
	app := &App{cfg: cfg}
	cleanups := make([]func(), 0)
	cleanup := func() {
		for i := len(cleanups) - 1; i >= 0; i-- {
			cleanups[i]()
		}
	}

	chain, err := middleware.NewChain(cfg)
	if err != nil {
		cleanup()
		return nil, nil, fmt.Errorf("init middleware chain: %w", err)
	}
	app.chain = chain

	app.resolver = controller.NewPathResolver(cfg.Downstream)
	app.proxy = controller.NewProxyController(app.resolver)
	app.health = controller.NewHealthController()

	return app, cleanup, nil
}
