// Code generated by hand (acts as the wire_gen.go replacement). DO NOT EDIT.
//
// This file is the non-wireinject counterpart to wire.go. It assembles the
// dependency graph manually so the service can be built without running the
// google/wire code generator. The structure mirrors what wire would emit.

package main

import (
	"fmt"
	"time"

	"github.com/redis/go-redis/v9"
	"gorm.io/driver/postgres"
	"gorm.io/gorm"
	gormlogger "gorm.io/gorm/logger"

	"tcm-history-ai/backend/pkg/rabbitmq"
	"tcm-history-ai/backend/user-service/internal/application/usecase"
	"tcm-history-ai/backend/user-service/internal/conf"
	"tcm-history-ai/backend/user-service/internal/controller"
	"tcm-history-ai/backend/user-service/internal/domain/event"
	"tcm-history-ai/backend/user-service/internal/domain/service"
	"tcm-history-ai/backend/user-service/internal/infrastructure/auth"
	"tcm-history-ai/backend/user-service/internal/infrastructure/cache"
	"tcm-history-ai/backend/user-service/internal/infrastructure/eventbus"
	"tcm-history-ai/backend/user-service/internal/infrastructure/persistence"
)

// App holds every wired dependency required to serve HTTP traffic.
type App struct {
	userRepo         *persistence.UserRepo
	roleRepo         *persistence.RoleRepo
	permRepo         *persistence.PermissionRepo
	profileRepo      *persistence.ProfileRepo
	settingsRepo     *persistence.SettingsRepo
	membershipPlanRepo  *persistence.MembershipPlanRepo
	userSubscriptionRepo *persistence.UserSubscriptionRepo
	membershipOrderRepo *persistence.MembershipOrderRepo
	apiKeyRepo       *persistence.ApiKeyRepo
	tenantRepo       *persistence.TenantRepo
	tenantMemberRepo *persistence.TenantMemberRepo

	authUC         *usecase.AuthUseCase
	profileUC      *usecase.ProfileUseCase
	settingsUC     *usecase.SettingsUseCase
	adminUC        *usecase.AdminUseCase
	roleUC         *usecase.RoleUseCase
	membershipPlanUC *usecase.MembershipPlanUseCase
	subscriptionUC *usecase.SubscriptionUseCase
	orderUC        *usecase.OrderUseCase
	apiKeyUC       *usecase.ApiKeyUseCase
	tenantUC       *usecase.TenantUseCase

	db        *gorm.DB
	redis     *redis.Client
	publisher event.EventPublisher
}

// ControllerDeps returns the bundle of controllers required by the router.
func (a *App) ControllerDeps() *controller.Deps {
	return &controller.Deps{
		Auth:       controller.NewAuthController(a.authUC),
		Profile:    controller.NewProfileController(a.profileUC),
		Settings:   controller.NewSettingsController(a.settingsUC),
		Admin:      controller.NewAdminController(a.adminUC),
		Role:       controller.NewRoleController(a.roleUC),
		Membership: controller.NewMembershipController(a.membershipPlanUC, a.subscriptionUC, a.orderUC),
		ApiKey:     controller.NewApiKeyController(a.apiKeyUC),
		Tenant:     controller.NewTenantController(a.tenantUC),
	}
}

// InitializeApp builds the full dependency graph from configuration.
// The returned cleanup function releases all acquired resources.
func InitializeApp(cfg *conf.Config) (*App, func(), error) {
	app := &App{}
	cleanups := make([]func(), 0)
	cleanup := func() {
		for i := len(cleanups) - 1; i >= 0; i-- {
			cleanups[i]()
		}
	}

	db, err := newDB(cfg)
	if err != nil {
		cleanup()
		return nil, nil, fmt.Errorf("open db: %w", err)
	}
	app.db = db

	// Repositories.
	app.userRepo = persistence.NewUserRepo(db)
	app.roleRepo = persistence.NewRoleRepo(db)
	app.permRepo = persistence.NewPermissionRepo(db)
	app.profileRepo = persistence.NewProfileRepo(db)
	app.settingsRepo = persistence.NewSettingsRepo(db)
	app.membershipPlanRepo = persistence.NewMembershipPlanRepo(db)
	app.userSubscriptionRepo = persistence.NewUserSubscriptionRepo(db)
	app.membershipOrderRepo = persistence.NewMembershipOrderRepo(db)
	app.apiKeyRepo = persistence.NewApiKeyRepo(db)
	app.tenantRepo = persistence.NewTenantRepo(db)
	app.tenantMemberRepo = persistence.NewTenantMemberRepo(db)

	// Redis client for the refresh token store. Connection is lazy: a missing
	// broker surfaces as a logged warning on the first refresh, not as a
	// startup failure.
	app.redis = redis.NewClient(&redis.Options{
		Addr:     fmt.Sprintf("%s:%d", cfg.Redis.Host, cfg.Redis.Port),
		Password: cfg.Redis.Password,
		DB:       cfg.Redis.DB,
	})
	refreshStore := cache.NewRedisRefreshTokenStore(app.redis)

	// Auth adapters.
	hasher := auth.NewBcryptPasswordHasher()
	tokens := auth.NewJWTTokenManager(cfg.JWT.Secret, cfg.JWT.AccessTokenTTL, cfg.JWT.RefreshTokenTTL)

	// RabbitMQ publisher. The underlying AMQP connection is opened lazily so
	// a missing broker does not break service startup.
	rmqCfg := rabbitmq.Config{
		Host:     cfg.RabbitMQ.Host,
		Port:     cfg.RabbitMQ.Port,
		User:     cfg.RabbitMQ.User,
		Password: cfg.RabbitMQ.Password,
		VHost:    cfg.RabbitMQ.VHost,
	}
	app.publisher = eventbus.NewRabbitMQEventPublisher(rmqCfg)
	if pub, ok := app.publisher.(*eventbus.RabbitMQEventPublisher); ok {
		cleanups = append(cleanups, func() { _ = pub.Close() })
	}

	// Use cases.
	app.authUC = usecase.NewAuthUseCase(
		app.userRepo,
		app.roleRepo,
		app.profileRepo,
		app.settingsRepo,
		hasher,
		tokens,
		refreshStore,
		app.publisher,
	)
	app.profileUC = usecase.NewProfileUseCase(app.userRepo, app.profileRepo, app.publisher)
	app.settingsUC = usecase.NewSettingsUseCase(app.settingsRepo)
	app.adminUC = usecase.NewAdminUseCase(app.userRepo, app.roleRepo, app.permRepo)
	app.roleUC = usecase.NewRoleUseCase(app.roleRepo, app.permRepo)
	app.membershipPlanUC = usecase.NewMembershipPlanUseCase(app.membershipPlanRepo)
	app.subscriptionUC = usecase.NewSubscriptionUseCase(app.membershipPlanRepo, app.userSubscriptionRepo, app.membershipOrderRepo, app.apiKeyRepo)
	app.orderUC = usecase.NewOrderUseCase(app.membershipOrderRepo, app.membershipPlanRepo)
	app.apiKeyUC = usecase.NewApiKeyUseCase(app.apiKeyRepo)
	app.tenantUC = usecase.NewTenantUseCase(app.tenantRepo, app.tenantMemberRepo)

	// Compile-time interface checks: ensure concrete adapters satisfy the
	// domain ports. These are no-ops at runtime.
	var (
		_ service.PasswordHasher    = hasher
		_ service.TokenManager      = tokens
		_ service.RefreshTokenStore = refreshStore
		_ event.EventPublisher      = app.publisher
	)

	cleanups = append(cleanups, func() {
		sqlDB, _ := db.DB()
		if sqlDB != nil {
			_ = sqlDB.Close()
		}
	})
	cleanups = append(cleanups, func() {
		_ = app.redis.Close()
	})

	return app, cleanup, nil
}

// newDB opens a GORM *gorm.DB using the Postgres driver.
func newDB(cfg *conf.Config) (*gorm.DB, error) {
	level := gormlogger.Warn
	switch cfg.DB.LogLevel {
	case "silent":
		level = gormlogger.Silent
	case "error":
		level = gormlogger.Error
	case "warn":
		level = gormlogger.Warn
	case "info":
		level = gormlogger.Info
	}
	gormCfg := &gorm.Config{
		Logger: gormlogger.Default.LogMode(level),
	}
	db, err := gorm.Open(postgres.Open(cfg.DB.DSN()), gormCfg)
	if err != nil {
		return nil, err
	}
	sqlDB, err := db.DB()
	if err != nil {
		return nil, err
	}
	if cfg.DB.MaxOpenConns > 0 {
		sqlDB.SetMaxOpenConns(cfg.DB.MaxOpenConns)
	}
	if cfg.DB.MaxIdleConns > 0 {
		sqlDB.SetMaxIdleConns(cfg.DB.MaxIdleConns)
	}
	if cfg.DB.ConnMaxLifetime > 0 {
		sqlDB.SetConnMaxLifetime(time.Duration(cfg.DB.ConnMaxLifetime) * time.Second)
	}
	return db, nil
}
