// Code generated by hand (acts as the wire_gen.go replacement). DO NOT EDIT.
//
// This file is the non-wireinject counterpart to wire.go. It assembles the
// dependency graph manually so the service can be built without running the
// google/wire code generator. The structure mirrors what wire would emit.

package main

import (
	"context"
	"fmt"
	"time"

	"gorm.io/driver/postgres"
	"gorm.io/gorm"
	gormlogger "gorm.io/gorm/logger"

	"tcm-history-ai/backend/knowledge-service/internal/application/usecase"
	"tcm-history-ai/backend/knowledge-service/internal/conf"
	"tcm-history-ai/backend/knowledge-service/internal/controller"
	"tcm-history-ai/backend/knowledge-service/internal/domain/event"
	"tcm-history-ai/backend/knowledge-service/internal/domain/service"
	"tcm-history-ai/backend/knowledge-service/internal/infrastructure/embedding"
	"tcm-history-ai/backend/knowledge-service/internal/infrastructure/eventbus"
	"tcm-history-ai/backend/knowledge-service/internal/infrastructure/milvus"
	"tcm-history-ai/backend/knowledge-service/internal/infrastructure/persistence"
	"tcm-history-ai/backend/knowledge-service/internal/infrastructure/rerank"
	"tcm-history-ai/backend/knowledge-service/internal/infrastructure/search"
	"tcm-history-ai/backend/knowledge-service/internal/infrastructure/storage"
	"tcm-history-ai/backend/pkg/rabbitmq"
)

// App holds every wired dependency required to serve HTTP traffic.
type App struct {
	docRepo    *persistence.DocumentRepo
	chunkRepo  *persistence.DocumentChunkRepo
	taskRepo   *persistence.EmbeddingTaskRepo
	queryRepo  *persistence.RagQueryRepo

	docUC      *usecase.DocumentUseCase
	chunkUC    *usecase.ChunkUseCase
	retrievalUC *usecase.RetrievalUseCase
	taskUC     *usecase.TaskUseCase

	db        *gorm.DB
	vector    *milvus.Client
	meili     *search.MeiliClient
	embedder  service.EmbeddingProvider
	reranker  service.Reranker
	minio     *storage.MinIOClient
	publisher event.EventPublisher
}

// ControllerDeps returns the bundle of controllers required by the router.
func (a *App) ControllerDeps() *controller.Deps {
	return &controller.Deps{
		Document:  controller.NewDocumentController(a.docUC),
		Chunk:     controller.NewChunkController(a.chunkUC),
		Retrieval: controller.NewRetrievalController(a.retrievalUC),
		Task:      controller.NewTaskController(a.taskUC),
	}
}

// InitializeApp builds the full dependency graph from configuration.
// The returned cleanup function releases all acquired resources.
func InitializeApp(cfg *conf.Config) (*App, func(), error) {
	app := &App{}
	cleanups := make([]func(), 0)
	cleanup := func() {
		for i := len(cleanups) - 1; i >= 0; i-- {
			cleanups[i]()
		}
	}

	db, err := newDB(cfg)
	if err != nil {
		cleanup()
		return nil, nil, fmt.Errorf("open db: %w", err)
	}
	app.db = db

	// Repositories.
	app.docRepo = persistence.NewDocumentRepo(db)
	app.chunkRepo = persistence.NewDocumentChunkRepo(db)
	app.taskRepo = persistence.NewEmbeddingTaskRepo(db)
	app.queryRepo = persistence.NewRagQueryRepo(db)

	// Vector store (Milvus). 在 enabled=false 时为内存 stub。
	app.vector = milvus.New(milvus.Config{
		Host:       cfg.Milvus.Host,
		Port:       cfg.Milvus.Port,
		Collection: cfg.Milvus.Collection,
		Dim:        cfg.Milvus.Dim,
		Username:   cfg.Milvus.Username,
		Password:   cfg.Milvus.Password,
		Enabled:    cfg.Milvus.Enabled,
	})
	_ = app.vector.EnsureCollection(context.Background())

	// Full-text search (Meilisearch).
	app.meili = search.NewMeiliClient(cfg.Meili.Host, cfg.Meili.Port, cfg.Meili.APIKey, cfg.Meili.IndexPrefix)
	_ = app.meili.EnsureIndex()

	// Embedding provider.
	embedder, err := embedding.New(embedding.Config{
		Provider: cfg.Embedding.Provider,
		Endpoint: cfg.Embedding.Endpoint,
		APIKey:   cfg.Embedding.APIKey,
		Model:    cfg.Embedding.Model,
		Dim:      cfg.Embedding.Dim,
		Timeout:  cfg.Embedding.Timeout,
	})
	if err != nil {
		cleanup()
		return nil, nil, fmt.Errorf("init embedding provider: %w", err)
	}
	app.embedder = embedder

	// Reranker.
	app.reranker = rerank.New()

	// MinIO. 双 bucket：original + markdown。
	mc, err := storage.NewMinIOClient(
		cfg.MinIO.Endpoint, cfg.MinIO.AccessKey, cfg.MinIO.SecretKey,
		cfg.MinIO.OriginalBucket, cfg.MinIO.MarkdownBucket, cfg.MinIO.UseSSL,
	)
	if err != nil {
		cleanup()
		return nil, nil, fmt.Errorf("init minio: %w", err)
	}
	app.minio = mc
	// Best-effort bucket creation; a missing broker must not block startup.
	_ = mc.EnsureBuckets(context.Background())

	// Event publisher (RabbitMQ).
	rmqCfg := rabbitmq.Config{
		Host:     cfg.RabbitMQ.Host,
		Port:     cfg.RabbitMQ.Port,
		User:     cfg.RabbitMQ.User,
		Password: cfg.RabbitMQ.Password,
		VHost:    cfg.RabbitMQ.VHost,
	}
	pub := eventbus.NewRabbitMQEventPublisher(rmqCfg)
	app.publisher = pub
	cleanups = append(cleanups, func() { _ = pub.Close() })

	// Use cases.
	app.docUC = usecase.NewDocumentUseCase(app.docRepo, app.publisher)
	app.chunkUC = usecase.NewChunkUseCase(app.chunkRepo, app.docRepo)
	app.taskUC = usecase.NewTaskUseCase(app.taskRepo)
	app.retrievalUC = usecase.NewRetrievalUseCase(
		app.chunkRepo, app.queryRepo,
		app.vector, app.meili, app.embedder, app.reranker,
		cfg.Milvus.TopK, cfg.Milvus.RRFK, cfg.Milvus.RerankTopK,
	)

	cleanups = append(cleanups, func() {
		sqlDB, _ := db.DB()
		if sqlDB != nil {
			_ = sqlDB.Close()
		}
	})

	return app, cleanup, nil
}

// newDB opens a GORM *gorm.DB using the Postgres driver.
func newDB(cfg *conf.Config) (*gorm.DB, error) {
	level := gormlogger.Warn
	switch cfg.DB.LogLevel {
	case "silent":
		level = gormlogger.Silent
	case "error":
		level = gormlogger.Error
	case "warn":
		level = gormlogger.Warn
	case "info":
		level = gormlogger.Info
	}
	gormCfg := &gorm.Config{
		Logger: gormlogger.Default.LogMode(level),
	}
	db, err := gorm.Open(postgres.Open(cfg.DB.DSN()), gormCfg)
	if err != nil {
		return nil, err
	}
	sqlDB, err := db.DB()
	if err != nil {
		return nil, err
	}
	if cfg.DB.MaxOpenConns > 0 {
		sqlDB.SetMaxOpenConns(cfg.DB.MaxOpenConns)
	}
	if cfg.DB.MaxIdleConns > 0 {
		sqlDB.SetMaxIdleConns(cfg.DB.MaxIdleConns)
	}
	if cfg.DB.ConnMaxLifetime > 0 {
		sqlDB.SetConnMaxLifetime(time.Duration(cfg.DB.ConnMaxLifetime) * time.Second)
	}
	return db, nil
}
